CREATE TABLE IF NOT EXISTS product (
id SERIAL NOT NULL,
quantity NUMERIC(9, 3) NOT NULL,

PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS discount_card (
id SERIAL NOT NULL,
number CHARACTER VARYING(9) NOT NULL,

PRIMARY KEY(id)
);